baseURL: https://metalogueur.github.io/metalogueur/design_evaluation_ux
copyright: "&copy; 2022 [Benoit Hamel](https://www.metalogueur.com)"
defaultContentLanguage: fr
languageCode: fr-ca
title: Design et évaluation UX
theme: PaperMod
enableRobotsTXT: true
enableEmoji: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

params:
  env: "production" # production to enable google analytics, opengraph, twitter-cards and schema.
  title: Design et évaluation UX
  description: "Réflexions, travaux et portfolio UX liés au MicroMasters Design et Évaluation UX de HEC Montréal"
  keywords: [expérience utilisateur, user experience, ux, edX, HEC Montréal]
  author: Benoit Hamel
  # author: ["Me", "You"] # multiple authors
  # images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "2 January 2006"
  defaultTheme: dark
  disableThemeToggle: false
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false
  images: "img/profile-picture.png"

  assets:
    disableHLJS: true # to disable highlight.js
    disableFingerprinting: true
    favicon: "/favicon.ico"
    favicon16x16: "/favicon-16x16.png"
    favicon32x32: "/favicon-32x32.png"
    apple_touch_icon: "/apple-touch-icon.png"
    # safari_pinned_tab: "<link / abs url>"

  label:
    text: "Design et évaluation UX"
    # icon: /apple-touch-icon.png
    # iconHeight: 35

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: "Design et évaluation UX"
    subtitle: "Réflexions, travaux et portfolio UX liés au MicroMasters de HEC Montréal"
    imageUrl: "img/profile-picture.png"
    imageWidth: 192
    imageHeight: 192
    imageTitle: Benoit Hamel
    buttons:
      - name: Réflexions
        url: /reflexions
      - name: Travaux
        url: /travaux
      - name: Portfolio
        url: /portfolio

  # home-info mode
  # homeInfoParams:
  #  Title: "Bonjour \U0001F44B !"
  #  Content: Bienvenue sur mon terrain de jeu!

  socialIcons:
    # - name: twitter
    #   url: "https://twitter.com/"
    # - name: stackoverflow
    #   url: "https://stackoverflow.com"
    # - name: linkedin
    #   url: "https://ca.linkedin.com/in/benoit-hamel"
    # - name: github
    #   url: "https://github.com/metalogueur"

  analytics:
    # google:
    #   SiteVerificationTag: "XYZabc"
    # bing:
    #   SiteVerificationTag: "XYZabc"
    # yandex:
    #   SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  # editPost:
  #  URL: "https://github.com/<path_to_repo>/content"
  #  Text: "Suggest Changes" # edit text
  #  appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

  schema:
    publisherType: Person

menu:
  main:
    - identifier: reflexions
      name: Réflexions
      url: /reflexions/
      weight: 10
    - identifier: travaux
      name: Travaux
      url: /travaux/
      weight: 20
    - identifier: portfolio
      name: Portfolio
      url: /portfolio/
      weight: 30
    - identifier: a-propos
      name: À propos
      url: /a-propos/
      weight: 40
    - identifier: edx
      name: "Le programme"
      url: "https://www.edx.org/micromasters/hecmontrealx-design-et-evaluation"
      weight: 50
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai
# Search config
outputs:
  home:
    - HTML
    - RSS
    - JSON